In [1]:
import pandas as pd
import glob
import os

# Set your folder path here
folder_path = "C:/Users/kylea/iCloudDrive/EAE/Data Science/final project/ny_metro_manhattan_chunks/raw_data"

# Get all CSV file paths in the folder
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

# Read and concatenate all CSVs into a single DataFrame
combined_df = pd.concat(
    (pd.read_csv(f) for f in csv_files),
    ignore_index=True
)

# Optional: quick preview
print(f"✅ Loaded {len(csv_files)} CSVs into a DataFrame with {combined_df.shape[0]:,} rows and {combined_df.shape[1]} columns.")
combined_df.head()

✅ Loaded 818 CSVs into a DataFrame with 12,444,955 rows and 9 columns.

,transit_timestamp,transit_mode,station_complex_id,station_complex,borough,payment_method,fare_class_category,ridership,transfers
0,2021-09-23T03:00:00.000,subway,316,50 St (1),Manhattan,metrocard,Metrocard - Unlimited 7-Day,8.0,0.0
1,2022-07-22T19:00:00.000,subway,323,Christopher St-Sheridan Sq (1),Manhattan,metrocard,Metrocard - Full Fare,111.0,1.0
2,2022-07-22T19:00:00.000,subway,323,Christopher St-Sheridan Sq (1),Manhattan,metrocard,Metrocard - Other,9.0,0.0
3,2021-09-23T12:00:00.000,subway,403,33 St (6),Manhattan,metrocard,Metrocard - Full Fare,193.0,8.0
4,2021-09-23T07:00:00.000,subway,602,"14 St-Union Sq (L,N,Q,R,W,4,5,6)",Manhattan,metrocard,Metrocard - Seniors & Disability,35.0,10.0